### ISSUE TITLE
"Invalid key length" error displayed

### ISSUE THREAD

**Issue by cloudcompute** [Hylozoic/hylo-redux#33]
When I enter a correct user name and password in the Login window and presses the Go button, it displays the "Invalid key length" error and I cannot do browse any other part of the app.

**Comment by levity** [comment]
Hi ramandhingra. Are you talking about next.hylo.com? Or are you trying to run the Hylo code locally?

**Comment by cloudcompute** [comment]
I am trying to run it locally

**Comment by levity** [comment]
Did you get a stack trace from the hylo-node app? If so, please share it. It is probably related to one of the environment variables not being set correctly.

**Comment by cloudcompute** [comment]
Here is the stack trace. Yes the error is there:

10:16:23 PM web.1 |  info: select "users".\* from "users" where "id" = 4 limit 1
10:16:23 PM web.1 |  info: select "users_community".\* from "users_community" left join "community" on "community"."id" = "users_community"."community_id" where "users_community"."active" = true and "community"."active" = true and "users_community"."user_id" in (4)
10:16:23 PM web.1 |  info: select "users_skill".\* from "users_skill" where "users_skill"."user_id" in (4)
10:16:23 PM web.1 |  info: select "users_org".\* from "users_org" where "users_org"."user_id" in (4)
10:16:23 PM web.1 |  info: select "phones".\* from "phones" where "phones"."user_id" in (4)
10:16:23 PM web.1 |  info: select "emails".\* from "emails" where "emails"."user_id" in (4)
10:16:23 PM web.1 |  info: select "websites".\* from "websites" where "websites"."user_id" in (4)
10:16:23 PM web.1 |  info: select "linked_account".\* from "linked_account" where "linked_account"."user_id" in (4)
10:16:23 PM web.1 |  info: select "tours".\* from "tours" where "type" = onboarding and "tours"."user_id" in (4)
10:16:23 PM web.1 |  error: Sending 500 ("Server Error") response:
10:16:23 PM web.1 |   Error: Invalid key length
10:16:23 PM web.1 |      at Error (native)
10:16:23 PM web.1 |      at new Cipheriv (crypto.js:187:16)
10:16:23 PM web.1 |      at Object.Cipheriv (crypto.js:185:12)
10:16:23 PM web.1 |      at Object.encrypt (PlayCrypto.js:11:25)
10:16:23 PM web.1 |      at Object.wrapper (/home/user/SmartServices/hylo-node/node_modules/sails/node_modules/lodash/index.js:3095:19)
10:16:23 PM web.1 |      at Function.encryptEmail (User.js:270:41)
10:16:23 PM web.1 |      at [object Object].encryptedEmail (User.js:119:17)
10:16:23 PM web.1 |      at extraAttributes (UserPresenter.js:15:24)
10:16:23 PM web.1 |      at [object Object].<anonymous> (UserPresenter.js:48:47)
10:16:23 PM web.1 |      at processImmediate [as _immediateCallback](timers.js:383:17)
10:16:23 PM web.1 |  From previous event:
10:16:23 PM web.1 |      at Object.fetchForSelf (UserPresenter.js:48:6)
10:16:23 PM web.1 |      at Object.findSelf (UserController.js:72:26)
10:16:23 PM web.1 |      at wrapper (/home/user/SmartServices/hylo-node/node_modules/sails/node_modules/lodash/index.js:3095:19)
10:16:23 PM web.1 |      at routeTargetFnWrapper (/home/user/SmartServices/hylo-node/node_modules/sails/lib/router/bind.js:179:5)
10:16:23 PM web.1 |      at callbacks (/home/user/SmartServices/hylo-node/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
10:16:23 PM web.1 |      at param (/home/user/SmartServices/hylo-node/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
10:16:23 PM web.1 |      at pass (/home/user/SmartServices/hylo-node/node_modules/sails/node_modules/express/lib/router/index.js:145:5)

**Comment by levity** [comment]
Ah, right. The environment variable PLAY_APP_SECRET needs to be 16
characters or longer.

**Comment by cloudcompute** [comment]
Thanks It worked.
